----------------------------- Job Portal ---------------------------------------
CREATE TABLE "HR"."TRN_USERS" 
("USER_ID" NUMBER(10,0), 
"USER_NAME" VARCHAR2(50 BYTE), 
"EMAIL" VARCHAR2(60 BYTE), 
"CREATE_PASSWORD" VARCHAR2(10 BYTE), 
"PHONE_NO" VARCHAR2(10 BYTE), 
"CREATED_DATE" TIMESTAMP (6));

Insert into HR.TRN_USERS (USER_ID,USER_NAME,EMAIL,CREATE_PASSWORD,PHONE_NO,CREATED_DATE) values (1004,'karthikeyeni','karthikeyeni1997@gmail.com','karthi17','7200253333',to_timestamp('21-05-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'));
Insert into HR.TRN_USERS (USER_ID,USER_NAME,EMAIL,CREATE_PASSWORD,PHONE_NO,CREATED_DATE) values (1008,'durgadevi','ammudd308@gmail.com','durga','9876567898',to_timestamp('23-05-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'));
Insert into HR.TRN_USERS (USER_ID,USER_NAME,EMAIL,CREATE_PASSWORD,PHONE_NO,CREATED_DATE) values (1007,'Ishwarya','ishwarya15127@gmail.com','ishwarya','9876567898',to_timestamp('23-05-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'));

ALTER TABLE "HR"."TRN_USERS" MODIFY ("USER_NAME" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS" MODIFY ("CREATE_PASSWORD" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS" MODIFY ("PHONE_NO" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS" ADD UNIQUE ("USER_NAME");

ALTER TABLE "HR"."TRN_USERS" ADD UNIQUE ("EMAIL");
  
ALTER TABLE "HR"."TRN_USERS" ADD CONSTRAINT "TRN_USER_ID_PK" PRIMARY KEY ("USER_ID");

COMMIT;

CREATE TABLE "HR"."TRN_USERS_PROFILE" 
("PROFILE_ID" NUMBER(10,0), 
"DATE_OF_BIRTH" DATE, 
"GENDER" CHAR(1 BYTE), 
"ADDRESS" VARCHAR2(60 BYTE), 
"EDUCATION_DEGREE" VARCHAR2(40 BYTE), 
"COLLEGE_NAME" VARCHAR2(60 BYTE), 
"MARIAL_STATUS" VARCHAR2(10 BYTE), 
"YR_OF_COMPLETION" NUMBER(10,0), 
"RELOCATE" VARCHAR2(10 BYTE), 
"USER_ID" NUMBER(10,0), 
"CREATED_BY" NUMBER(10,0), 
"CREATED_DATE" TIMESTAMP (6), 
"MODIFIED_BY" NUMBER(10,0), 
"MODIFIED_DATE" TIMESTAMP (6), 
"PINCODE" NUMBER(10,0));

Insert into HR.TRN_USERS_PROFILE (PROFILE_ID,DATE_OF_BIRTH,GENDER,ADDRESS,EDUCATION_DEGREE,COLLEGE_NAME,MARIAL_STATUS,YR_OF_COMPLETION,RELOCATE,USER_ID,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,PINCODE) values (2,to_date('12-05-97','DD-MM-RR'),'F','madurai','BE/CSE','SITE','unmarried',2019,'yes',1007,1007,to_timestamp('23-05-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),1007,to_timestamp('23-05-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),641077);
Insert into HR.TRN_USERS_PROFILE (PROFILE_ID,DATE_OF_BIRTH,GENDER,ADDRESS,EDUCATION_DEGREE,COLLEGE_NAME,MARIAL_STATUS,YR_OF_COMPLETION,RELOCATE,USER_ID,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,PINCODE) values (3,to_date('17-08-96','DD-MM-RR'),'F','Coimbatore','BE/CSE','SITE','unmarried',2019,'yes',1008,1008,to_timestamp('23-05-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),1008,to_timestamp('23-05-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),641047);

ALTER TABLE "HR"."TRN_USERS_PROFILE" MODIFY ("DATE_OF_BIRTH" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_PROFILE" MODIFY ("GENDER" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_PROFILE" MODIFY ("ADDRESS" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_PROFILE" MODIFY ("EDUCATION_DEGREE" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_PROFILE" MODIFY ("COLLEGE_NAME" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_PROFILE" MODIFY ("RELOCATE" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_PROFILE" MODIFY ("CREATED_BY" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_PROFILE" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_PROFILE" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_PROFILE" MODIFY ("MODIFIED_DATE" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_PROFILE" MODIFY ("PINCODE" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_PROFILE" ADD CONSTRAINT "TRN_PROFILE_ID_PK" PRIMARY KEY ("PROFILE_ID");

COMMIT;

CREATE TABLE "HR"."TRN_USERS_PROJECT" 
("PROJECT_ID" NUMBER(10,0), 
"TITLE" VARCHAR2(40 BYTE), 
"DETAILS" VARCHAR2(60 BYTE), 
"SKILLS" VARCHAR2(50 BYTE), 
"USER_ID" NUMBER(10,0), 
"CREATED_BY" NUMBER(10,0), 
"CREATED_DATE" TIMESTAMP (6), 
"MODIFIED_BY" NUMBER(10,0), 
"MODIFIED_DATE" TIMESTAMP (6), 
"DURATION" VARCHAR2(30 BYTE));

Insert into HR.TRN_USERS_PROJECT (PROJECT_ID,TITLE,DETAILS,SKILLS,USER_ID,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,DURATION) values (1,'Course management ','Online courses','Java,SQL',1007,1007,to_timestamp('23-05-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),1007,to_timestamp('23-05-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),'1 month');

ALTER TABLE "HR"."TRN_USERS_PROJECT" MODIFY ("TITLE" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_PROJECT" MODIFY ("DETAILS" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_PROJECT" MODIFY ("SKILLS" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_PROJECT" MODIFY ("CREATED_BY" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_PROJECT" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_PROJECT" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_PROJECT" MODIFY ("MODIFIED_DATE" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_PROJECT" ADD CONSTRAINT "TRN_PROJECT_ID_PK" PRIMARY KEY ("PROJECT_ID");
 
COMMIT;

CREATE TABLE "HR"."TRN_USERS_LANGUAGE" 
("LANGUAGE_ID" NUMBER(10,0), 
"LANGUAGE_KNOWN" VARCHAR2(40 BYTE), 
"PROFICIENCY" VARCHAR2(40 BYTE), 
"USER_ID" NUMBER(10,0), 
"CREATED_BY" NUMBER(10,0), 
"CREATED_DATE" TIMESTAMP (6), 
"MODIFIED_BY" NUMBER(10,0), 
"MODIFIED_DATE" TIMESTAMP (6));

Insert into HR.TRN_USERS_LANGUAGE (LANGUAGE_ID,LANGUAGE_KNOWN,PROFICIENCY,USER_ID,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (2,'English,Tamil','None',1007,1007,to_timestamp('23-05-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),1007,to_timestamp('23-05-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'));
Insert into HR.TRN_USERS_LANGUAGE (LANGUAGE_ID,LANGUAGE_KNOWN,PROFICIENCY,USER_ID,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE) values (1,'English,Tamil','None',1007,1007,to_timestamp('23-05-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),1007,to_timestamp('23-05-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'));

ALTER TABLE "HR"."TRN_USERS_LANGUAGE" MODIFY ("LANGUAGE_KNOWN" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_LANGUAGE" MODIFY ("CREATED_BY" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_LANGUAGE" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_LANGUAGE" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_LANGUAGE" MODIFY ("MODIFIED_DATE" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_LANGUAGE" ADD CONSTRAINT "TRN_LANGUAGE_ID_PK" PRIMARY KEY ("LANGUAGE_ID");

COMMIT;

CREATE TABLE "HR"."TRN_USERS_FUNCTIONAL" 
("FUNCTIONAL_ID" NUMBER(10,0), 
"INDUSTRY" VARCHAR2(50 BYTE), 
"DEPARTMENT" VARCHAR2(40 BYTE), 
"ROLE" VARCHAR2(30 BYTE), 
"EMPLOYMENT_TYPE" VARCHAR2(30 BYTE), 
"LOCATION" VARCHAR2(50 BYTE), 
"USER_ID" NUMBER(10,0), 
"CREATED_BY" NUMBER(10,0), 
"CREATED_DATE" TIMESTAMP (6), 
"MODIFIED_BY" NUMBER(10,0), 
"MODIFIED_DATE" TIMESTAMP (6), 
"JOB_TYPE" VARCHAR2(30 BYTE));

Insert into HR.TRN_USERS_FUNCTIONAL (FUNCTIONAL_ID,INDUSTRY,DEPARTMENT,ROLE,EMPLOYMENT_TYPE,LOCATION,USER_ID,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,JOB_TYPE) values (1,'IT-Hardware and Networking','IT-Software ERP/CRM','Web designer','option1','Chennai',1007,1007,to_timestamp('23-05-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),1007,to_timestamp('23-05-19 12:00:00.000000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),'option1');

ALTER TABLE "HR"."TRN_USERS_FUNCTIONAL" MODIFY ("INDUSTRY" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_FUNCTIONAL" MODIFY ("DEPARTMENT" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_FUNCTIONAL" MODIFY ("ROLE" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_FUNCTIONAL" MODIFY ("EMPLOYMENT_TYPE" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_FUNCTIONAL" MODIFY ("LOCATION" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_FUNCTIONAL" MODIFY ("CREATED_BY" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_FUNCTIONAL" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_FUNCTIONAL" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_FUNCTIONAL" MODIFY ("MODIFIED_DATE" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USERS_FUNCTIONAL" ADD CONSTRAINT "TRN_FUNCTIONAL_ID_PK" PRIMARY KEY ("FUNCTIONAL_ID");

COMMIT;

CREATE TABLE "HR"."TRN_USER_JOBINFO" 
("JOBINFO_ID" NUMBER(10,0), 
"USER_ID" NUMBER(10,0), 
"COMPANY_ID" NUMBER(10,0), 
"SAVE_JOB" NUMBER(10,0) DEFAULT 0, 
"APPLY_JOB" NUMBER(10,0) DEFAULT 0, 
"CREATED_BY" NUMBER(10,0), 
"CREATED_DATE" DATE, 
"SHORTLIST" VARCHAR2(30 BYTE) DEFAULT 0);

Insert into HR.TRN_USER_JOBINFO (JOBINFO_ID,USER_ID,COMPANY_ID,SAVE_JOB,APPLY_JOB,CREATED_BY,CREATED_DATE,SHORTLIST) values (39,1004,5,0,1,1004,to_date('23-05-19','DD-MM-RR'),'1');
Insert into HR.TRN_USER_JOBINFO (JOBINFO_ID,USER_ID,COMPANY_ID,SAVE_JOB,APPLY_JOB,CREATED_BY,CREATED_DATE,SHORTLIST) values (36,1007,5,0,1,1007,to_date('23-05-19','DD-MM-RR'),'1');
Insert into HR.TRN_USER_JOBINFO (JOBINFO_ID,USER_ID,COMPANY_ID,SAVE_JOB,APPLY_JOB,CREATED_BY,CREATED_DATE,SHORTLIST) values (34,1007,1,0,1,1007,to_date('23-05-19','DD-MM-RR'),'1');
Insert into HR.TRN_USER_JOBINFO (JOBINFO_ID,USER_ID,COMPANY_ID,SAVE_JOB,APPLY_JOB,CREATED_BY,CREATED_DATE,SHORTLIST) values (35,1007,3,0,1,1007,to_date('23-05-19','DD-MM-RR'),'0');
Insert into HR.TRN_USER_JOBINFO (JOBINFO_ID,USER_ID,COMPANY_ID,SAVE_JOB,APPLY_JOB,CREATED_BY,CREATED_DATE,SHORTLIST) values (37,1008,1,0,1,1008,to_date('23-05-19','DD-MM-RR'),'1');
Insert into HR.TRN_USER_JOBINFO (JOBINFO_ID,USER_ID,COMPANY_ID,SAVE_JOB,APPLY_JOB,CREATED_BY,CREATED_DATE,SHORTLIST) values (38,1008,3,0,1,1008,to_date('23-05-19','DD-MM-RR'),'1');

ALTER TABLE "HR"."TRN_USER_JOBINFO" ADD CONSTRAINT "JOBINFO_ID_PK" PRIMARY KEY ("JOBINFO_ID");

ALTER TABLE "HR"."TRN_USER_JOBINFO" MODIFY ("CREATED_BY" NOT NULL ENABLE);
 
ALTER TABLE "HR"."TRN_USER_JOBINFO" MODIFY ("CREATED_DATE" NOT NULL ENABLE);

COMMIT;

create sequence trn_functional_id_seq 
start with 1
increment by 1;

create sequence trn_language_id_seq 
start with 1
increment by 1;

create sequence trn_user_id_seq 
start with 1000
increment by 1;

create sequence trn_profile_id_seq 
start with 1
increment by 1;

create sequence trn_functional_id_seq 
start with 1
increment by 1;

create sequence trn_project_id_seq 
start with 1
increment by 1;

create sequence trn_recruiters_id_seq
start with 1
increment by 1;

CREATE SEQUENCE login_id_seq
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE jobinfo_id_seq
START WITH 1
INCREMENT BY 1;

COMMIT;
--------------------------------------------------------------------------------