/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.73
 * Generated at: 2019-05-24 05:39:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<!-- Font Awesome -->\n");
      out.write("<link\n");
      out.write("\thref=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\"\n");
      out.write("\trel=\"stylesheet\" id=\"bootstrap-css\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Kaushan+Script\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("<link\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\"\n");
      out.write("\trel=\"stylesheet\"\n");
      out.write("\tintegrity=\"sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN\"\n");
      out.write("\tcrossorigin=\"anonymous\">\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>Login</title>\n");
      out.write("<style>\n");
      out.write("body {\n");
      out.write("\tpadding-top: 3.2rem;\n");
      out.write("\tpadding-bottom: 4.2rem;\n");
      out.write("\tpadding-left: 50rem;\n");
      out.write("\tbackground-image: url(\"image/j2.png\");\n");
      out.write("\tbackground-repeat: no-repeat;\n");
      out.write("\tbackground-attachment: fixed;\n");
      out.write("\tbackground-size: 1400px 800px;\n");
      out.write("\tbackground-opacity: 0.2;\n");
      out.write("}\n");
      out.write("h1 {\n");
      out.write("\tfont-family: 'Kaushan Script', cursive;\n");
      out.write("\ttext-align: center;\n");
      out.write("}\n");
      out.write("h4 {\n");
      out.write("font-family: 'Kaushan Script', cursive;\n");
      out.write("\ttext-align: center;\n");
      out.write("}\n");
      out.write(".myform {\n");
      out.write("\tpadding: 1rem;\n");
      out.write("\twidth: 100%;\n");
      out.write("\tbackground-color: #fff;\n");
      out.write("\tbackground-clip: padding-box;\n");
      out.write("\tborder: 1px solid rgba(0, 0, 0, .2);\n");
      out.write("\tborder-radius: 1.1rem;\n");
      out.write("}\n");
      out.write(".mybtn {\n");
      out.write("\tborder-radius: 50px;\n");
      out.write("}\n");
      out.write(".login-or {\n");
      out.write("\tposition: relative;\n");
      out.write("\tcolor: #aaa;\n");
      out.write("\tmargin-top: 10px;\n");
      out.write("\tmargin-bottom: 10px;\n");
      out.write("\tpadding-top: 10px;\n");
      out.write("\tpadding-bottom: 10px;\n");
      out.write("}\n");
      out.write(".span-or {\n");
      out.write("\tdisplay: block;\n");
      out.write("\tposition: absolute;\n");
      out.write("\tleft: 50%;\n");
      out.write("\ttop: -2px;\n");
      out.write("\tmargin-left: -25px;\n");
      out.write("\tbackground-color: #fff;\n");
      out.write("\twidth: 50px;\n");
      out.write("\ttext-align: center;\n");
      out.write("}\n");
      out.write(".hr-or {\n");
      out.write("\theight: 1px;\n");
      out.write("\tmargin-top: 0px !important;\n");
      out.write("\tmargin-bottom: 0px !important;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<body>\n");
      out.write("<h1>Joodle Jobs</h1>\n");
      out.write("<div class=\"container\">\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<div class=\"col-md-9 mx-auto\">\n");
      out.write("\t\t\t\t<div id=\"first\">\n");
      out.write("\t\t\t\t\t<div class=\"myform form \">\n");
      out.write("\t\t\t\t\t\t<div class=\"logo mb-3\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12 text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t<h1>Login</h1>\n");
      out.write("\t\t\t\t\t\t\t</div>\t\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<form action=\"LoginServlet\" method=\"post\" name=\"login\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"email\">Email Id</label> <input type=\"email\"\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"email\" class=\"form-control\" id=\"email\"\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Enter Email\" autofocus title=\"abc12@gmail.com\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tpattern=\"[a-z0-9]+@[a-z]+.[a-z]{2,}\" required>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"password\">Password</label> <input type=\"password\"\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"password\" id=\"password\" class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Enter Password\" pattern=\"[a-z0-9]{4,8}\" required>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12 text-center \">\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\"\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\" btn btn-block mybtn btn-primary tx-tfm\">Login</button>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<h4>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ERROR}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</h4>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12 \">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"login-or\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<hr class=\"hr-or\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"span-or\">or</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<!-- <div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\tDon't you remember your password? <a href=\"forgotpassword.html\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"forgotpassword\">Click here</a>\n");
      out.write("\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t</div> -->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\tDon't have account? <a href=\"registeration.jsp\" id=\"signup\">Sign\n");
      out.write("\t\t\t\t\t\t\t\t\t\tup here</a>\n");
      out.write("\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</form>\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
